# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev", "imp/tests" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Setup firefox
      id: setup-firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest
    - run: |
        echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
        firefox --version
        
    - name: Download GeckoDriver
      run: curl -L https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz -o /home/runner/work/frontend/frontend/geckodriver.tar.gz
    - name: Extract GeckoDriver
      run: tar -xvzf /home/runner/work/frontend/frontend/geckodriver.tar.gz
    - name: Export to path
      run: export PATH="$PATH:/home/runner/work/frontend/frontend/geckodriver"
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
